### ISSUE TITLE
TBomb Request

### ISSUE THREAD

**Issue by TheSpeedX** [darkestentropy/bombcrack#1]
Hello
I know you are a developer like me @darkestentropy ....

i hope that you analyzed the code and i am sure you can say that there is no malware hidden as @scpketer said

And you currently know the security concerns if it will be used without any limits

So i request you to kindly take it down

I know its an easy obfuscation as maintaining TBomb by adding new APIs became harder for me
So i did not much really care to obfuscate it more

Hope That You will understand

Any issues feel free to ping...

**Comment by darkestentropy** [comment]
I'm not taking any active effort for distributing neither TBomb nor this sort of open-source variant of it.

Take it as an inspired work, because:
* I **do not** include TBomb contents in this repo - check Makefile (lines [9-10](https://github.com/darkestentropy/bombcrack/blob/bb56b709d1e1bf32c552decf66924c57d006fe47/Makefile#L9)).
* I **do not** modify TBomb - script does not affect original files.

Issue will remain - I do my best not to take all the fame but credit you.

**Comment by darkestentropy** [comment]
### Thread is locked.
All further issues **not related to implementation of this project** will be deleted or closed, decision is to be made by the repository maintainers.
Direct questions at [entropial@protonmail.ch](mailto:entropial@protonmail.ch)

**Comment by darkestentropy** [comment]
Takedown request rejected, project is no longer using new TheSpeedX/TBomb content unless modified by end user.
